housesInformations = {
    0: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 0.0}},
    1: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 12.0}},
    2: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 24.0}},
    3: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 36.0}},
    4: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 48.0}},
    5: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 0.0}},
    6: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 12.0}},
    7: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 24.0}},
    8: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 36.0}},
    9: {   'informations': 'Sem informações ainda',
           'rent': {'ownerId': None, 'price': 48.0}},
    10: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 0.0}},
    11: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 12.0}},
    12: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 24.0}},
    13: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 36.0}},
    14: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 48.0}},
    15: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 0.0}},
    16: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 12.0}},
    17: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 24.0}},
    18: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 36.0}},
    19: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 48.0}},
    20: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 0.0}},
    21: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 12.0}},
    22: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 24.0}},
    23: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 36.0}},
    24: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 48.0}},
    25: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 0.0}},
    26: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 12.0}},
    27: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 24.0}},
    28: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 36.0}},
    29: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 48.0}},
    30: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 0.0}},
    31: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 12.0}},
    32: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 24.0}},
    33: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 36.0}},
    34: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 48.0}},
    35: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 0.0}},
    36: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 12.0}},
    37: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 24.0}},
    38: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 36.0}},
    39: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 48.0}},
    40: {   'informations': 'Sem informações ainda',
            'rent': {'ownerId': None, 'price': 0.0}}}